server:
  port: 8560
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

eureka:
  instance:
#    hostname: client
    status-page-url-path: /
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    preferIpAddress: true
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: client
